### ISSUE TITLE
New line \r\n is counted as 2 characters instead of one?

### ISSUE THREAD

**Issue by b0tm1nd** [asquared31415/cursor_pos#1]
Seems like when having a document with Windows new line character \r\n the extension counts as 2 symbols, but looks like supposed to be 1.
![2024-06-19_23-53](https://github.com/asquared31415/cursor_pos/assets/3400283/aee2ed15-018a-4e61-aee5-b8ced0f22dfa)

**Comment by asquared31415** [comment]
This is intentional.  The offset is the number of characters from the beginning of the file, and `\r` and `\n` are distinct characters that happen to work together when displayed.

I believe the discrepancy is because AST Explorer seems to be normalizing line endings to be only `\n`, even when you directly upload files or paste text.  For example, with the `typescript` parser selected, there's a `text` field that shows that only `\n` exists in the text.
